services:
  mysql-db:
    image: mysql:8.0
    platform: linux/amd64 # Asegurar compatibilidad con Mac M1
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Cambia este valor a tu preferencia
      MYSQL_DATABASE: herramientas_db # Cambia el nombre de la base de datos
      MYSQL_USER: fran # Cambia el nombre de usuario
      MYSQL_PASSWORD: fran # Cambia la contraseña del usuario
    ports:
      - "3306:3306" # Exponer el puerto 3306 para conexiones desde el host
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - mysql_network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_CREATE_TOPICS: "citas:1:1"
    ports:
      - "9092:9092"
    networks:
      - mysql_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
    networks:
      - mysql_network

  herramientas_svc:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mysql_network


volumes:
  db_data:
    driver: local

networks:
  mysql_network:
    driver: bridge
  my_network:
    driver: bridge
